query GetAssets($first: Int!, $after: String) {
  assets(first: $first, after: $after) {
    totalCount
    pageInfo {
      hasNextPage
      endCursor
    }
    nodes {
      id
      name
      assetType {
        id
        name
        category
        isSafetyRelevant
      }
      vendor
      model
      firmwareVersion
      serialNumber
      criticality
      role
      safetyRated

      ipAddresses
      macAddresses
      vlans

      zones {
        id
        name
      }

      firstSeen
      lastSeen
      isActive
      __typename
    }
  }
}
