query GetUsers($first: Int!, $after: String) {
  users(first: $first, after: $after) {
    pageInfo {
      hasNextPage
      endCursor
    }
    nodes {
      id
      username
      displayName
      email
      authType
      provider
      externalId

      role
      permissions
      isSystem
      isReadOnly

      enabled
      locked
      failedLoginAttempts

      createdAt
      lastLogin
      lastActivity
      passwordChangedAt

      groups {
        nodes {
          id
          name
        }
      }
    }
  }
}
