# queries/plugins_assets_field.py
#
# Tenable OT Security – PluginsAssetsField GraphQL Enum
#
# Source documentation:
# https://docs.tenable.com/OT-security/api/pluginsassetsfield.doc.html
#
# Purpose:
# - Enumerates selectable fields for Plugin ↔ Asset queries

PLUGINS_ASSETS_FIELD_ENUM_NAME = "PluginsAssetsField"

PLUGINS_ASSETS_FIELDS = [
    "id",
    "source",
    "family",
    "name",
    "severity",
    "vprScore",
    "vprLevel",
    "affectedAssets",
    "fixedAssets",
    "modificationDate",
    "comment",
    "owner",
    "cvss3Score",
    "firstSeen",
    "lastSeen",
    "lastHit",
    "lastSnapshot",
    "macs",
    "ips",
    "segments",
    "segmentsIds",
    "subnets",
    "type",
    "superType",
    "category",
    "purdueLevel",
    "vendor",
    "runStatus",
    "extendedRunStatus",
    "runStatusTime",
    "location",
    "description",
    "os",
    "model",
    "firmwareVersion",
    "serial",
    "slot",
    "hardwareState",
    "lifecycleStatus",
    "discontinuedDate",
    "replacementProduct",
    "backplane",
    "backplaneName",
    "risk",
    "criticality",
    "hidden",
    "lastUpdate",
    "sources",
    "tags",
    "customField1",
    "customField2",
    "customField3",
    "customField4",
    "customField5",
    "customField6",
    "customField7",
    "customField8",
    "customField9",
    "customField10",
    "assetId",
    "pluginId",
    "port",
    "protocol",
    "svcName",
    "time",
    "mitigatedAt",
    "mitigationDuration",
    "output",
    "status",
]
