# queries/policy_event_type.py
#
# Tenable OT Security – PolicyEventType GraphQL Enum
#
# Source documentation:
# https://docs.tenable.com/OT-security/api/policyeventtype.doc.html
#
# Purpose:
# - Enumerates all policy-driven event types for OT Security

POLICY_EVENT_TYPE_ENUM_NAME = "PolicyEventType"

POLICY_EVENT_TYPES = [
    "Unknown",

    "SimaticCodeDownload",
    "SimaticCodeUpload",
    "SimaticCodeDelete",
    "SimaticHardwareConfigurationDownload",
    "SimaticHardwareConfigurationUpload",
    "SimaticFirmwareDownload",
    "SimaticFirmwareUpload",
    "SimaticPlcStop",
    "SimaticPlcStart",
    "SimaticIoForcingEnable",
    "SimaticIoForcingDisable",
    "SimaticReplaceIOForces",
    "SimaticTagWrite",
    "SimaticFirmwareApply",
    "SimaticGoOnline",

    "ModiconPlcStart",
    "ModiconPlcStop",
    "ModiconFirmwareErase",
    "ModiconFirmwareDownload",
    "ModiconFirmwareUpload",
    "ModiconCodeDownload",
    "ModiconCodeUpload",
    "ModiconHardwareConfigurationDownload",
    "ModiconGoOnline",

    "RockwellPlcStart",
    "RockwellPlcStop",
    "RockwellModuleRestart",
    "RockwellPlcTest",
    "RockwellGoOnline",
    "RockwellCodeUpload",
    "RockwellCodeDownload",
    "RockwellFirmwareDownload",
    "RockwellTagCreate",
    "RockwellTaskCreate",
    "RockwellProgramCreate",
    "RockwellRoutineCreate",
    "RockwellTagDelete",
    "RockwellTaskDelete",
    "RockwellProgramDelete",
    "RockwellRoutineDelete",
    "RockwellRungDelete",
    "RockwellRename",
    "RockwellSfcForcingEnable",
    "RockwellSfcForcingDisable",
    "RockwellCodeEdit",
    "RockwellIoForcingEnable",
    "RockwellIoForcingDisable",

    "ApogeePlcColdstart",
    "ApogeeCodeDownload",
    "ApogeeCodeUpload",
    "ApogeeProgramReportUpload",
    "ApogeeCodeDiffDownload",
    "ApogeeSetPointStatus",

    "GePlcStop",
    "GePlcStart",
    "GePlcClear",
    "GeCodeDownload",
    "GeCodeUpload",
    "GeMonitorMode",
    "GeProgrammerMode",
    "GeGoOnline",

    "Abb800xACodeDownload",
    "Abb800xADeleteApplication",
    "Abb800xADeleteProject",
    "Abb800xAFirmwareDownload",
    "Abb800xAIoForcingEnable",
    "Abb800xAIoForcingDisable",
    "Abb800xAReplaceIOForces",
    "Abb800xAGoOnline",
    "Abb800xARedundancySwitchPrimary",
    "Abb800xARedundancyResetBackup",
    "Abb800xAEnableWebServer",
    "Abb800xAClearLatchedStatus",

    "DeltaVControllerDownload",
    "DeltaVModuleDownload",
    "DeltaVSetupDataDownload",
    "DeltaVColdRestartDownload",
    "DeltaVForceTransition",
    "DeltaVSwitchOver",
    "DeltaVEnterDebugMode",
    "DeltaVLeaveDebugMode",
    "DeltaVModuleRun",
    "DeltaVModuleRunOnce",
    "DeltaVModuleStop",
    "DeltaVSequenceStart",
    "DeltaVSequenceStop",
    "DeltaVSequenceReset",
    "DeltaVStepEnable",
    "DeltaVStepDisable",
    "DeltaVStepActivate",
    "DeltaVStepDeactivate",
    "DeltaVPlcCommission",
    "DeltaVPlcDecommission",
    "DeltaVFirmwareDownload",

    "NewAssetDiscovered",
    "NewModule",
    "IpConflict",
    "ArpScan",
    "SynScan",

    "InactiveAssetFiveMins",
    "InactiveAssetFifteenMins",
    "InactiveAssetThirtyMins",
    "InactiveAssetOneHour",
    "InactiveAssetThreeHours",
    "InactiveAssetTwelveHours",
    "InactiveAssetOneDay",
    "InactiveAssetOneWeek",

    "SnapshotDiff",
    "Conversation",
    "ModuleStateChange",
    "ModuleKeyStateChange",
    "FirmwareVersionChange",
    "UnauthorizedTagWrite",
    "OpenPort",
    "BaselineDeviation",
    "ModuleDisappeared",

    "RdpConnectionWithAuthentication",
    "RdpConnectionNoAuthentication",

    "IntrusionDetected",

    "ModbusExceptionIllegalFunction",
    "ModbusExceptionIllegalDataAddress",
    "ModbusExceptionIllegalDataValue",

    "DataSpikeDetected",
    "ConversationCountSpikeDetected",
    "UsbChange",

    "YokogawaCodeDownload",

    "AbbMasterbus300CodeDownload",
    "AbbMasterbus300CodeUpload",
    "AbbMasterbus300EngStationConnect",

    "IEC104StartDataTransfer",
    "IEC104StopDataTransfer",
    "IEC104InterrogationCommand",
    "IEC104CounterInterrogationCommand",
    "IEC104ClockSynchronizationCommand",
    "IEC104ResetProcessCommand",
    "IEC104TestCommandWithTimeTag",

    "ToyopucPlcStart",
    "ToyopucPlcResetStart",
    "ToyopucPlcStop",
    "ToyopucCodeDownload",
    "ToyopucCodeUpload",

    "MelsecQCodeDownload",
    "MelsecQCodeUpload",

    "DNP3FcSelect",
    "DNP3FcOperate",
    "DNP3FcDirectOperate",
    "DNP3FcDirectOperateNoResponse",
    "DNP3FcColdRestart",
    "DNP3FcWarmRestart",
    "DNP3FcInitializeData",
    "DNP3FcInitializeApplication",
    "DNP3FcStartApplication",
    "DNP3FcStopApplication",
    "DNP3FcEnableUnsolicitedResponses",
    "DNP3FcDisableUnsolicitedResponses",
    "DNP3FcOpenFile",
    "DNP3FcCloseFile",
    "DNP3FcDeleteFile",
    "DNP3FcAuthenticateFile",
    "DNP3FcActivateConfiguration",

    "DNP3iinFcNotImplemented",
    "DNP3iinObjectUnknown",
    "DNP3iinParamError",
    "DNP3iinBufferOverflow",
    "DNP3iinAlreadyExecuting",
    "DNP3iinCorruptConfig",

    "HoneywellPlcColdRestart",
    "HoneywellPlcWarmRestart",
    "HoneywellPlcStop",

    "FtpSuccessfulLogin",
    "FtpFailedLogin",
    "TelnetSuccessfulLogin",
    "TelnetFailedLogin",
    "TelnetLoginAttempt",

    "SaiaPlcStart",
    "SaiaPlcColdRestart",
    "SaiaPlcStop",
    "SaiaCodeDownload",
    "SaiaCodeUpload",

    "BachmannApplicationRun",
    "BachmannApplicationStop",
    "BachmannApplicationDownload",

    "BoschPsiConnect",
    "BoschPsiDisconnect",
    "BoschPsiDownloadConfig",
    "BoschPsiReset",

    "MmsDefineNamedVariableList",
    "MmsDeleteNamedVariableList",

    "ICCPCreateDataSet",
    "ICCPBilateralTableExchange",

    "RediscoveredAsset",

    "HoneywellCodeDownload",
    "HoneywellCodeUpload",
    "HoneywellForceEnable",
    "HoneywellForceDisable",

    "IEC61850SubscriptionFailure",
    "IEC61850UnauthorizedWrite",
]
