# queries/user_defined_asset_type.py
#
# Tenable OT Security – UserDefinedAssetType GraphQL Enum
#
# Source documentation:
# https://docs.tenable.com/OT-security/api/userdefinedassettype.doc.html
#
# Purpose:
# - Enumerates all supported user-defined asset types in Tenable OT Security

USER_DEFINED_ASSET_TYPE_ENUM_NAME = "UserDefinedAssetType"

USER_DEFINED_ASSET_TYPE = [
    "Unknown",
    "NetworkDevice",
    "Radio",
    "Repeater",
    "Converter",
    "Firewall",
    "AccessPoint",
    "Hub",
    "Gateway",
    "SerialEthernetBridge",
    "Switch",
    "Router",
    "OtDevice",
    "IndustrialPrinter",
    "IndustrialNetworkDevice",
    "IndustrialGateway",
    "IndustrialSwitch",
    "IndustrialRouter",
    "Iot",
    "Projector",
    "Panel",
    "StorageDevice",
    "VoipDevice",
    "Mobile",
    "MedicalDevice",
    "Tablet",
    "SmartTv",
    "SmartHub",
    "LightingControl",
    "HvacModule",
    "AccessControlSystem",
    "BarcodeScanner",
    "SmartSensor",
    "ThreeDPrinter",
    "Printer",
    "Ups",
    "Camera",
    "Server",
    "FileServer",
    "WebServer",
    "VirtualServer",
    "VideoManagementSystem",
    "SecurityAppliance",
    "TenableIcp",
    "TenableEm",
    "TenableSensor",
    "DomainController",
    "FieldDevice",
    "Actuator",
    "Drive",
    "IndustrialSensor",
    "Inverter",
    "Relay",
    "RemoteIo",
    "PowerMeter",
    "OtServer",
    "Historian",
    "DataLogger",
    "Hmi",
    "Workstation",
    "VirtualWorkstation",
    "OtWorkstation",
    "Eng",
    "Controller",
    "BackplaneModule",
    "PowerSupply",
    "Io",
    "Cp",
    "Cnc",
    "Robot",
    "Bms",
    "Rtu",
    "Ied",
    "Dcs",
    "Plc",
    "_RemoveUserDefinedValue",
]
